[2025-08-29 19:21:35,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-29T17:18:28.703256+00:00 [queued]>
[2025-08-29 19:21:35,978] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-29T17:18:28.703256+00:00 [queued]>
[2025-08-29 19:21:35,979] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-29 19:21:35,979] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2025-08-29 19:21:35,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-29 19:21:36,004] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-29 17:18:28.703256+00:00
[2025-08-29 19:21:36,010] {standard_task_runner.py:52} INFO - Started process 445 to run task
[2025-08-29 19:21:36,016] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'scheduled__2025-08-29T17:18:28.703256+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmp989a7i_u', '--error-file', '/tmp/tmpkvxijnr9']
[2025-08-29 19:21:36,018] {standard_task_runner.py:80} INFO - Job 356: Subtask fetch_and_send_weather
[2025-08-29 19:21:36,055] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-29 19:21:36,125] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-29T17:18:28.703256+00:00 [running]> on host a4b544519f2b
[2025-08-29 19:21:36,263] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-29T17:18:28.703256+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-29T17:18:28.703256+00:00
[2025-08-29 19:21:36,264] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-29 19:21:36,265] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-29 19:21:36,293] {subprocess.py:85} INFO - Output:
[2025-08-29 19:21:40,907] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 28, 'humidity': 74, 'windSpeed': 3.6, 'cloudCover': 98, 'rainIntensity': 0, 'timestamp': '2025-08-29T19:21:00Z'}
[2025-08-29 19:21:41,039] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-29 19:21:41,116] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250829T171828, start_date=20250829T192135, end_date=20250829T192141
[2025-08-29 19:21:41,152] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-29 19:21:41,218] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
