[2025-08-18 13:26:47,248] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-08-18T11:22:48.013844+00:00 [queued]>
[2025-08-18 13:26:47,267] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-08-18T11:22:48.013844+00:00 [queued]>
[2025-08-18 13:26:47,267] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-18 13:26:47,267] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2025-08-18 13:26:47,267] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-18 13:26:47,293] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stream_hdfs> on 2025-08-18 11:22:48.013844+00:00
[2025-08-18 13:26:47,299] {standard_task_runner.py:52} INFO - Started process 5049 to run task
[2025-08-18 13:26:47,304] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'stream_hdfs', 'scheduled__2025-08-18T11:22:48.013844+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpgsef7hv2', '--error-file', '/tmp/tmpr89j4rpd']
[2025-08-18 13:26:47,306] {standard_task_runner.py:80} INFO - Job 290: Subtask stream_hdfs
[2025-08-18 13:26:47,339] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-18 13:26:47,392] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-08-18T11:22:48.013844+00:00 [running]> on host a4b544519f2b
[2025-08-18 13:26:47,525] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=stream_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2025-08-18T11:22:48.013844+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-18T11:22:48.013844+00:00
[2025-08-18 13:26:47,526] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-18 13:26:47,527] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n/home/***/.local/bin/spark-submit   --master local[*]   --conf spark.hadoop.fs.defaultFS=hdfs://namenode:9000   --conf spark.hadoop.dfs.client.use.datanode.hostname=true   --conf spark.sql.adaptive.enabled=false   --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1   /opt/***/scripts/pyspark/streaming.py']
[2025-08-18 13:26:47,544] {subprocess.py:85} INFO - Output:
[2025-08-18 13:26:47,573] {subprocess.py:92} INFO - /opt/spark-3.3.1-bin-hadoop3/bin/load-spark-env.sh: line 68: ps: command not found
[2025-08-18 13:26:49,663] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/opt/spark-3.3.1-bin-hadoop3/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-08-18 13:26:49,778] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-08-18 13:26:49,778] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-08-18 13:26:49,783] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-08-18 13:26:49,784] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-7163f96e-6796-4771-a4ce-11e849b0da83;1.0
[2025-08-18 13:26:49,784] {subprocess.py:92} INFO - 	confs: [default]
[2025-08-18 13:26:49,995] {subprocess.py:92} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 in spark-list
[2025-08-18 13:26:50,057] {subprocess.py:92} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 in central
[2025-08-18 13:26:50,085] {subprocess.py:92} INFO - 	found org.apache.kafka#kafka-clients;2.8.1 in central
[2025-08-18 13:26:50,112] {subprocess.py:92} INFO - 	found org.lz4#lz4-java;1.8.0 in spark-list
[2025-08-18 13:26:50,135] {subprocess.py:92} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-08-18 13:26:50,154] {subprocess.py:92} INFO - 	found org.slf4j#slf4j-api;1.7.32 in central
[2025-08-18 13:26:50,215] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
[2025-08-18 13:26:50,228] {subprocess.py:92} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-08-18 13:26:50,251] {subprocess.py:92} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.2 in central
[2025-08-18 13:26:50,270] {subprocess.py:92} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-08-18 13:26:50,282] {subprocess.py:92} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-08-18 13:26:50,307] {subprocess.py:92} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-08-18 13:26:50,330] {subprocess.py:92} INFO - :: resolution report :: resolve 534ms :: artifacts dl 12ms
[2025-08-18 13:26:50,330] {subprocess.py:92} INFO - 	:: modules in use:
[2025-08-18 13:26:50,330] {subprocess.py:92} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-08-18 13:26:50,330] {subprocess.py:92} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-08-18 13:26:50,330] {subprocess.py:92} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-08-18 13:26:50,330] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.apache.kafka#kafka-clients;2.8.1 from central in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 from spark-list in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 from central in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.lz4#lz4-java;1.8.0 from spark-list in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.slf4j#slf4j-api;1.7.32 from central in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.spark-project.spark#unused;1.0.0 from central in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-08-18 13:26:50,331] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-08-18 13:26:50,332] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-08-18 13:26:50,332] {subprocess.py:92} INFO - 	|      default     |   12  |   0   |   0   |   0   ||   12  |   0   |
[2025-08-18 13:26:50,332] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-08-18 13:26:50,337] {subprocess.py:92} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-7163f96e-6796-4771-a4ce-11e849b0da83
[2025-08-18 13:26:50,337] {subprocess.py:92} INFO - 	confs: [default]
[2025-08-18 13:26:50,345] {subprocess.py:92} INFO - 	0 artifacts copied, 12 already retrieved (0kB/8ms)
[2025-08-18 13:26:50,652] {subprocess.py:92} INFO - 25/08/18 13:26:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-18 13:26:52,068] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Running Spark version 3.3.1
[2025-08-18 13:26:52,104] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO ResourceUtils: ==============================================================
[2025-08-18 13:26:52,104] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-18 13:26:52,105] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO ResourceUtils: ==============================================================
[2025-08-18 13:26:52,105] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Submitted application: KafkaToHDFSWeather
[2025-08-18 13:26:52,130] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-18 13:26:52,142] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO ResourceProfile: Limiting resource is cpu
[2025-08-18 13:26:52,142] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-18 13:26:52,219] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SecurityManager: Changing view acls to: ***
[2025-08-18 13:26:52,219] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18 13:26:52,220] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SecurityManager: Changing view acls groups to:
[2025-08-18 13:26:52,220] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SecurityManager: Changing modify acls groups to:
[2025-08-18 13:26:52,220] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-08-18 13:26:52,510] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO Utils: Successfully started service 'sparkDriver' on port 45793.
[2025-08-18 13:26:52,547] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkEnv: Registering MapOutputTracker
[2025-08-18 13:26:52,591] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-18 13:26:52,611] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-18 13:26:52,612] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-18 13:26:52,617] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-18 13:26:52,648] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0527b098-8b05-40e4-8165-bf24fda7dee0
[2025-08-18 13:26:52,673] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-18 13:26:52,691] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-18 13:26:52,945] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-18 13:26:52,995] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at spark://a4b544519f2b:45793/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:52,995] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at spark://a4b544519f2b:45793/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:52,996] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at spark://a4b544519f2b:45793/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1755523612053
[2025-08-18 13:26:52,996] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at spark://a4b544519f2b:45793/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:52,996] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at spark://a4b544519f2b:45793/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1755523612053
[2025-08-18 13:26:52,996] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at spark://a4b544519f2b:45793/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:52,996] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at spark://a4b544519f2b:45793/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:52,996] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at spark://a4b544519f2b:45793/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1755523612053
[2025-08-18 13:26:52,997] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at spark://a4b544519f2b:45793/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1755523612053
[2025-08-18 13:26:52,997] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at spark://a4b544519f2b:45793/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1755523612053
[2025-08-18 13:26:52,997] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at spark://a4b544519f2b:45793/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:52,997] {subprocess.py:92} INFO - 25/08/18 13:26:52 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at spark://a4b544519f2b:45793/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1755523612053
[2025-08-18 13:26:53,000] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,001] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-08-18 13:26:53,017] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar at file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,018] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-08-18 13:26:53,025] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar at file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,026] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-08-18 13:26:53,039] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar at file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,040] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-08-18 13:26:53,045] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar at file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,046] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.commons_commons-pool2-2.11.1.jar
[2025-08-18 13:26:53,051] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar at file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,052] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.spark-project.spark_unused-1.0.0.jar
[2025-08-18 13:26:53,058] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:53,059] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-08-18 13:26:53,123] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar at file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,123] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.lz4_lz4-java-1.8.0.jar
[2025-08-18 13:26:53,130] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar at file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1755523612053
[2025-08-18 13:26:53,131] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-08-18 13:26:53,143] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar at file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1755523612053
[2025-08-18 13:26:53,143] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.slf4j_slf4j-api-1.7.32.jar
[2025-08-18 13:26:53,151] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar at file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:53,151] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-08-18 13:26:53,187] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO SparkContext: Added file file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar at file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1755523612053
[2025-08-18 13:26:53,187] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Copying /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/commons-logging_commons-logging-1.1.3.jar
[2025-08-18 13:26:53,304] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Starting executor ID driver on host a4b544519f2b
[2025-08-18 13:26:53,314] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-08-18 13:26:53,334] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1755523612053
[2025-08-18 13:26:53,360] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/commons-logging_commons-logging-1.1.3.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/commons-logging_commons-logging-1.1.3.jar
[2025-08-18 13:26:53,366] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,367] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.spark-project.spark_unused-1.0.0.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.spark-project.spark_unused-1.0.0.jar
[2025-08-18 13:26:53,372] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,377] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-08-18 13:26:53,382] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:53,398] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-08-18 13:26:53,404] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:53,430] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-08-18 13:26:53,435] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1755523612053
[2025-08-18 13:26:53,436] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.slf4j_slf4j-api-1.7.32.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.slf4j_slf4j-api-1.7.32.jar
[2025-08-18 13:26:53,444] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,446] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.lz4_lz4-java-1.8.0.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.lz4_lz4-java-1.8.0.jar
[2025-08-18 13:26:53,452] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,453] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.apache.commons_commons-pool2-2.11.1.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.commons_commons-pool2-2.11.1.jar
[2025-08-18 13:26:53,461] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,462] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/com.google.code.findbugs_jsr305-3.0.0.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-08-18 13:26:53,466] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,467] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-08-18 13:26:53,473] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,481] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.apache.kafka_kafka-clients-2.8.1.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-08-18 13:26:53,486] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching file:///home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1755523612053
[2025-08-18 13:26:53,489] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /home/***/.ivy2/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-08-18 13:26:53,499] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,556] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO TransportClientFactory: Successfully created connection to a4b544519f2b/172.20.0.2:45793 after 39 ms (0 ms spent in bootstraps)
[2025-08-18 13:26:53,571] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp14485376922950907753.tmp
[2025-08-18 13:26:53,637] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp14485376922950907753.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-08-18 13:26:53,647] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-sql-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-08-18 13:26:53,647] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/com.google.code.findbugs_jsr305-3.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,648] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/com.google.code.findbugs_jsr305-3.0.0.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp1728136068971724880.tmp
[2025-08-18 13:26:53,657] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp1728136068971724880.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/com.google.code.findbugs_jsr305-3.0.0.jar
[2025-08-18 13:26:53,665] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/com.google.code.findbugs_jsr305-3.0.0.jar to class loader
[2025-08-18 13:26:53,666] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.apache.kafka_kafka-clients-2.8.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,666] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.apache.kafka_kafka-clients-2.8.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp1544025348374660614.tmp
[2025-08-18 13:26:53,704] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp1544025348374660614.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.kafka_kafka-clients-2.8.1.jar
[2025-08-18 13:26:53,711] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.kafka_kafka-clients-2.8.1.jar to class loader
[2025-08-18 13:26:53,711] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.lz4_lz4-java-1.8.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,712] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.lz4_lz4-java-1.8.0.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp9370506804573059527.tmp
[2025-08-18 13:26:53,718] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp9370506804573059527.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.lz4_lz4-java-1.8.0.jar
[2025-08-18 13:26:53,725] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.lz4_lz4-java-1.8.0.jar to class loader
[2025-08-18 13:26:53,725] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,726] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp9965909508595081069.tmp
[2025-08-18 13:26:53,729] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp9965909508595081069.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar
[2025-08-18 13:26:53,735] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.3.1.jar to class loader
[2025-08-18 13:26:53,735] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:53,736] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.apache.hadoop_hadoop-client-api-3.3.2.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp1638956749134886080.tmp
[2025-08-18 13:26:53,841] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp1638956749134886080.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-api-3.3.2.jar
[2025-08-18 13:26:53,849] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-api-3.3.2.jar to class loader
[2025-08-18 13:26:53,849] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar with timestamp 1755523612053
[2025-08-18 13:26:53,850] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.xerial.snappy_snappy-java-1.1.8.4.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp11157450811406534256.tmp
[2025-08-18 13:26:53,863] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp11157450811406534256.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.xerial.snappy_snappy-java-1.1.8.4.jar
[2025-08-18 13:26:53,869] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.xerial.snappy_snappy-java-1.1.8.4.jar to class loader
[2025-08-18 13:26:53,870] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/commons-logging_commons-logging-1.1.3.jar with timestamp 1755523612053
[2025-08-18 13:26:53,870] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/commons-logging_commons-logging-1.1.3.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp2684839738284962452.tmp
[2025-08-18 13:26:53,873] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp2684839738284962452.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/commons-logging_commons-logging-1.1.3.jar
[2025-08-18 13:26:53,879] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/commons-logging_commons-logging-1.1.3.jar to class loader
[2025-08-18 13:26:53,879] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.apache.commons_commons-pool2-2.11.1.jar with timestamp 1755523612053
[2025-08-18 13:26:53,880] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.apache.commons_commons-pool2-2.11.1.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp8167634232241692403.tmp
[2025-08-18 13:26:53,883] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp8167634232241692403.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.commons_commons-pool2-2.11.1.jar
[2025-08-18 13:26:53,889] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.commons_commons-pool2-2.11.1.jar to class loader
[2025-08-18 13:26:53,889] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.spark-project.spark_unused-1.0.0.jar with timestamp 1755523612053
[2025-08-18 13:26:53,890] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.spark-project.spark_unused-1.0.0.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp3369325803560599469.tmp
[2025-08-18 13:26:53,893] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp3369325803560599469.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.spark-project.spark_unused-1.0.0.jar
[2025-08-18 13:26:53,899] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.spark-project.spark_unused-1.0.0.jar to class loader
[2025-08-18 13:26:53,899] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar with timestamp 1755523612053
[2025-08-18 13:26:53,900] {subprocess.py:92} INFO - 25/08/18 13:26:53 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp6963620526011992037.tmp
[2025-08-18 13:26:54,028] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp6963620526011992037.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar
[2025-08-18 13:26:54,039] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.apache.hadoop_hadoop-client-runtime-3.3.2.jar to class loader
[2025-08-18 13:26:54,039] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO Executor: Fetching spark://a4b544519f2b:45793/jars/org.slf4j_slf4j-api-1.7.32.jar with timestamp 1755523612053
[2025-08-18 13:26:54,039] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO Utils: Fetching spark://a4b544519f2b:45793/jars/org.slf4j_slf4j-api-1.7.32.jar to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp12086945590861519307.tmp
[2025-08-18 13:26:54,042] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO Utils: /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/fetchFileTemp12086945590861519307.tmp has been previously copied to /tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.slf4j_slf4j-api-1.7.32.jar
[2025-08-18 13:26:54,048] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO Executor: Adding file:/tmp/spark-f92f63fa-047d-485f-a9f8-55b1384e9db7/userFiles-3d715f68-8377-4a49-9a17-e0d0bc75ecd5/org.slf4j_slf4j-api-1.7.32.jar to class loader
[2025-08-18 13:26:54,060] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38593.
[2025-08-18 13:26:54,060] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO NettyBlockTransferService: Server created on a4b544519f2b:38593
[2025-08-18 13:26:54,063] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-18 13:26:54,073] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a4b544519f2b, 38593, None)
[2025-08-18 13:26:54,078] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO BlockManagerMasterEndpoint: Registering block manager a4b544519f2b:38593 with 434.4 MiB RAM, BlockManagerId(driver, a4b544519f2b, 38593, None)
[2025-08-18 13:26:54,081] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a4b544519f2b, 38593, None)
[2025-08-18 13:26:54,083] {subprocess.py:92} INFO - 25/08/18 13:26:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a4b544519f2b, 38593, None)
[2025-08-18 13:26:54,687] {subprocess.py:92} INFO - Connexion à Kafka...
[2025-08-18 13:26:57,282] {subprocess.py:92} INFO - Connexion Kafka réussie (kafka:9092)
[2025-08-18 13:26:57,283] {subprocess.py:92} INFO - Transformation des données JSON...
[2025-08-18 13:26:57,585] {subprocess.py:92} INFO - Démarrage du streaming vers HDFS...
[2025-08-18 13:26:58,668] {subprocess.py:92} INFO - Streaming actif - Données météo sauvegardées dans HDFS:/data/weather
[2025-08-18 14:20:45,179] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 219, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-08-18 14:22:17,599] {base_job.py:229} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 201, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2877, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2950, in _merge
    merged = self.get(mapper.class_, key[1], identity_token=key[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2702, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1669, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2025-08-18 14:22:28,150] {local_task_job.py:144} ERROR - Heartbeat time limit exceeded!
[2025-08-18 14:22:28,785] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5049. PIDs of all processes in the group: [5050, 5103, 5049]
[2025-08-18 14:22:28,829] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5049
[2025-08-18 14:22:28,901] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-18 14:22:28,907] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2025-08-18 14:22:30,854] {process_utils.py:75} INFO - Process psutil.Process(pid=5103, status='terminated', started='13:26:50') (5103) terminated with exit code None
[2025-08-18 14:22:38,816] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 189, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 90, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-18 14:22:38,904] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=send_weather_to_kafka, task_id=stream_hdfs, execution_date=20250818T112248, start_date=20250818T132647, end_date=20250818T142238
[2025-08-18 14:22:39,310] {standard_task_runner.py:97} ERROR - Failed to execute job 290 for task stream_hdfs (Task received SIGTERM signal; 5049)
[2025-08-18 14:22:39,386] {process_utils.py:75} INFO - Process psutil.Process(pid=5049, status='terminated', exitcode=1, started='13:26:47') (5049) terminated with exit code 1
[2025-08-18 14:22:41,654] {process_utils.py:75} INFO - Process psutil.Process(pid=5050, status='terminated', started='13:26:47') (5050) terminated with exit code None
