[2025-08-19 04:07:05,778] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-19T02:07:01.870913+00:00 [queued]>
[2025-08-19 04:07:05,792] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-19T02:07:01.870913+00:00 [queued]>
[2025-08-19 04:07:05,792] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-19 04:07:05,792] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-19 04:07:05,792] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-19 04:07:05,811] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): verify_pipeline> on 2025-08-19 02:07:01.870913+00:00
[2025-08-19 04:07:05,817] {standard_task_runner.py:52} INFO - Started process 12572 to run task
[2025-08-19 04:07:05,822] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'verify_pipeline', 'scheduled__2025-08-19T02:07:01.870913+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpzm0kqqc_', '--error-file', '/tmp/tmpcgxkv6tr']
[2025-08-19 04:07:05,823] {standard_task_runner.py:80} INFO - Job 324: Subtask verify_pipeline
[2025-08-19 04:07:05,849] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-19 04:07:05,895] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-19T02:07:01.870913+00:00 [running]> on host a4b544519f2b
[2025-08-19 04:07:05,990] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=verify_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2025-08-19T02:07:01.870913+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-19T02:07:01.870913+00:00
[2025-08-19 04:07:05,991] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-19 04:07:05,991] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            echo " Attente traitement Logstash..." && sleep 30 &&\n            curl -s "http://elasticsearch:9200/_cat/indices/weather*" || echo "Pas encore d\'index weather"\n        ']
[2025-08-19 04:07:06,003] {subprocess.py:85} INFO - Output:
[2025-08-19 04:07:06,006] {subprocess.py:92} INFO -  Attente traitement Logstash...
[2025-08-19 04:07:36,074] {subprocess.py:92} INFO - yellow open weather_data BQjbDtS5TvO1Q2HrAJGyvA 1 1 80 0 39kb 39kb
[2025-08-19 04:07:36,078] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-19 04:07:36,124] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=verify_pipeline, execution_date=20250819T020701, start_date=20250819T040705, end_date=20250819T040736
[2025-08-19 04:07:36,140] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-08-19 04:07:36,144] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 12572. PIDs of all processes in the group: [12572]
[2025-08-19 04:07:36,145] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 12572
[2025-08-19 04:07:36,146] {process_utils.py:75} INFO - Process psutil.Process(pid=12572, status='terminated', exitcode=0, started='04:07:04') (12572) terminated with exit code 0
