[2025-09-01 10:45:48,962] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-09-01T10:15:43.386020+00:00 [queued]>
[2025-09-01 10:45:48,982] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-09-01T10:15:43.386020+00:00 [queued]>
[2025-09-01 10:45:48,982] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 10:45:48,982] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-09-01 10:45:48,982] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 10:45:49,003] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): verify_pipeline> on 2025-09-01 10:15:43.386020+00:00
[2025-09-01 10:45:49,011] {standard_task_runner.py:52} INFO - Started process 13210 to run task
[2025-09-01 10:45:49,016] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'verify_pipeline', 'scheduled__2025-09-01T10:15:43.386020+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmp3dhli6wz', '--error-file', '/tmp/tmp4vzokl88']
[2025-09-01 10:45:49,018] {standard_task_runner.py:80} INFO - Job 517: Subtask verify_pipeline
[2025-09-01 10:45:49,042] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01 10:45:49,106] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-09-01T10:15:43.386020+00:00 [running]> on host e66737cfc193
[2025-09-01 10:45:49,254] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=verify_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T10:15:43.386020+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-01T10:15:43.386020+00:00
[2025-09-01 10:45:49,256] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-01 10:45:49,256] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            echo " Attente traitement Logstash..." && sleep 30 &&\n            curl -s "http://elasticsearch:9200/_cat/indices/weather*" || echo "Pas encore d\'index weather"\n        ']
[2025-09-01 10:45:49,272] {subprocess.py:85} INFO - Output:
[2025-09-01 10:45:49,275] {subprocess.py:92} INFO -  Attente traitement Logstash...
[2025-09-01 10:46:19,298] {subprocess.py:92} INFO - yellow open weather_data BQjbDtS5TvO1Q2HrAJGyvA 1 1 112 0 48.1kb 48.1kb
[2025-09-01 10:46:19,301] {subprocess.py:96} INFO - Command exited with return code 0
[2025-09-01 10:46:19,366] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=verify_pipeline, execution_date=20250901T101543, start_date=20250901T104548, end_date=20250901T104619
[2025-09-01 10:46:19,391] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-09-01 10:46:19,395] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 13210. PIDs of all processes in the group: [13210]
[2025-09-01 10:46:19,396] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 13210
[2025-09-01 10:46:19,403] {process_utils.py:75} INFO - Process psutil.Process(pid=13210, status='terminated', exitcode=0, started='10:45:48') (13210) terminated with exit code 0
