[2025-08-31 23:43:07,973] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-31T23:43:07.182344+00:00 [queued]>
[2025-08-31 23:43:07,987] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-31T23:43:07.182344+00:00 [queued]>
[2025-08-31 23:43:07,987] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-31 23:43:07,987] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-31 23:43:07,987] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-31 23:43:08,009] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-31 23:43:07.182344+00:00
[2025-08-31 23:43:08,018] {standard_task_runner.py:52} INFO - Started process 1769 to run task
[2025-08-31 23:43:08,024] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'manual__2025-08-31T23:43:07.182344+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpac8afwy6', '--error-file', '/tmp/tmp3qtzgbij']
[2025-08-31 23:43:08,026] {standard_task_runner.py:80} INFO - Job 391: Subtask fetch_and_send_weather
[2025-08-31 23:43:08,106] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-31T23:43:07.182344+00:00 [running]> on host 5d7670b258c3
[2025-08-31 23:43:08,211] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-31T23:43:07.182344+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-31T23:43:07.182344+00:00
[2025-08-31 23:43:08,212] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-31 23:43:08,212] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-31 23:43:08,227] {subprocess.py:85} INFO - Output:
[2025-08-31 23:43:09,818] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 29, 'humidity': 79, 'windSpeed': 1, 'cloudCover': 100, 'rainIntensity': 0, 'timestamp': '2025-08-31T23:43:00Z'}
[2025-08-31 23:43:09,905] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-31 23:43:09,956] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250831T234307, start_date=20250831T234307, end_date=20250831T234309
[2025-08-31 23:43:10,002] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-31 23:43:10,070] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
