[2025-09-01 00:52:44,606] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-09-01T00:52:44.050145+00:00 [queued]>
[2025-09-01 00:52:44,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-09-01T00:52:44.050145+00:00 [queued]>
[2025-09-01 00:52:44,632] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 00:52:44,632] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-09-01 00:52:44,632] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 00:52:44,674] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-09-01 00:52:44.050145+00:00
[2025-09-01 00:52:44,684] {standard_task_runner.py:52} INFO - Started process 458 to run task
[2025-09-01 00:52:44,691] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'manual__2025-09-01T00:52:44.050145+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpl1l2f8yt', '--error-file', '/tmp/tmp0giw57tb']
[2025-09-01 00:52:44,693] {standard_task_runner.py:80} INFO - Job 405: Subtask fetch_and_send_weather
[2025-09-01 00:52:44,802] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-09-01T00:52:44.050145+00:00 [running]> on host e66737cfc193
[2025-09-01 00:52:44,931] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T00:52:44.050145+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-01T00:52:44.050145+00:00
[2025-09-01 00:52:44,932] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-01 00:52:44,932] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-09-01 00:52:44,949] {subprocess.py:85} INFO - Output:
[2025-09-01 00:52:46,661] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 28, 'humidity': 84, 'windSpeed': 0, 'cloudCover': 100, 'rainIntensity': 0, 'timestamp': '2025-09-01T00:52:00Z'}
[2025-09-01 00:52:46,737] {subprocess.py:96} INFO - Command exited with return code 0
[2025-09-01 00:52:46,792] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250901T005244, start_date=20250901T005244, end_date=20250901T005246
[2025-09-01 00:52:46,830] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-09-01 00:52:46,923] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
