[2025-09-01 08:22:23,412] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-09-01T07:49:15.745356+00:00 [queued]>
[2025-09-01 08:22:23,425] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-09-01T07:49:15.745356+00:00 [queued]>
[2025-09-01 08:22:23,426] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 08:22:23,426] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-09-01 08:22:23,426] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-01 08:22:23,448] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): verify_pipeline> on 2025-09-01 07:49:15.745356+00:00
[2025-09-01 08:22:23,453] {standard_task_runner.py:52} INFO - Started process 11289 to run task
[2025-09-01 08:22:23,459] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'verify_pipeline', 'scheduled__2025-09-01T07:49:15.745356+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpa71wut1t', '--error-file', '/tmp/tmp4zwvrlp1']
[2025-09-01 08:22:23,460] {standard_task_runner.py:80} INFO - Job 498: Subtask verify_pipeline
[2025-09-01 08:22:23,492] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01 08:22:23,582] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-09-01T07:49:15.745356+00:00 [running]> on host e66737cfc193
[2025-09-01 08:22:23,757] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=verify_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T07:49:15.745356+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-01T07:49:15.745356+00:00
[2025-09-01 08:22:23,759] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-01 08:22:23,760] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            echo " Attente traitement Logstash..." && sleep 30 &&\n            curl -s "http://elasticsearch:9200/_cat/indices/weather*" || echo "Pas encore d\'index weather"\n        ']
[2025-09-01 08:22:23,777] {subprocess.py:85} INFO - Output:
[2025-09-01 08:22:23,780] {subprocess.py:92} INFO -  Attente traitement Logstash...
[2025-09-01 08:22:53,837] {subprocess.py:92} INFO - yellow open weather_data BQjbDtS5TvO1Q2HrAJGyvA 1 1 106 0 41.5kb 41.5kb
[2025-09-01 08:22:53,842] {subprocess.py:96} INFO - Command exited with return code 0
[2025-09-01 08:22:53,953] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=verify_pipeline, execution_date=20250901T074915, start_date=20250901T082223, end_date=20250901T082253
[2025-09-01 08:22:54,011] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-09-01 08:22:54,027] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 11289. PIDs of all processes in the group: [11289]
[2025-09-01 08:22:54,028] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 11289
[2025-09-01 08:22:54,029] {process_utils.py:75} INFO - Process psutil.Process(pid=11289, status='terminated', exitcode=0, started='08:22:22') (11289) terminated with exit code 0
